name: flutter_app1
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/logoIcon.png
      - images/weMet.png
      - images/weMet.png
      - images/fIcon.png
      - images/gIcon.png
      - images/bySigningUpForWe.png
      - images/phoneIcon.png
      - images/nameCardIcon.png
      - images/sexIcon.png
      - images/backIcon.png
      - images/emailIcon.png
      - images/birthIcon.png
      - images/introduceIcon.png
  fonts:
    - family: Manjariregular
      fonts:
        - asset: fonts/ManjariRegular.ttf
    - family: Manjaribold
      fonts:
        - asset: fonts/Manjari-Bold.ttf